name: Test
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install test dependencies
        run: sudo apt-get install shellcheck bats
      - name: Run shellcheck
        run: shellcheck git-find git-find.bats
      - name: Run the bats tests
        run: bats git-find.bats
